name: Release

on:
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod

    - name: Build
      run: make

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE: ${{ github.event.release.tag_name }}
      run: |
        gh release upload $RELEASE sig
