name: Release Please

on:
  push:
    branches:
    - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Run Release Please
      uses: google-github-actions/release-please-action@v3
      id: release
      with:
        command: manifest
        token: ${{ secrets.GITHUB_TOKEN }}
