name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Set up GitHub Hub
      run: go get -v github.com/github/hub

    - uses: actions/checkout@v1

    - name: Build
      run: make

    - name: Release
      run: |
        PATH=$PATH:$GOPATH/bin:$HOME/go/bin
        make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
